name: trading_example
description: Stock trading example using SamsaraBus Exchange Pattern
version: 1.0.0
publish_to: 'none' # Do not publish this example package

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  samsara_bus_dart: ^1.0.0
  samsara_bus_exchange_dart: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  samsara_bus_generator_dart:
    path: ../../