targets:
  $default:
    builders:
      samsara_bus_generator_dart|exchange:
        enabled: true

builders:
  exchange:
    import: "package:samsara_bus_generator_dart/exchange/builder.dart"
    builder_factories: ["samsaraBusExchangeGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
