name: samsara_bus_generator_dart
description: Code generator for SamsaraBus annotations
version: 1.0.0
repository: https://github.com/Samsara-Stream/samsara-bus-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.7.0
  dart_style: ^2.3.2
  source_gen: ^1.4.0
  samsara_bus_dart: ^1.0.0
  samsara_bus_exchange_dart: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  test: ^1.21.0