name: samsara_bus_dart
description: RxDart-based multi-topics message/event bus.
version: 1.0.0
repository: https://github.com/Samsara-Stream/samsara-bus-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  rxdart: ^0.28.0
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
