name: samsara_bus_exchange_dart
description: Exchange pattern annotations and helpers for Samsara Bus Dart.
version: 1.0.0
repository: https://github.com/Samsara-Stream/samsara-bus-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  samsara_bus_dart: ^1.0.0
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
