name: Publish to pub.dev

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
          flutter: false
          skipTests: true # Tests were run in a previous step
